touch foo_archive.7z
touch foo_archive.bz2
touch foo_archive.cab
touch foo_archive.img
touch foo_archive.iso
touch foo_archive.rar
touch foo_archive.sql
touch foo_archive.sqlite
touch foo_archive.tar.gz
touch foo_archive.tgz
touch foo_archive.xpi
touch foo_archive.zip
touch foo_audio.m3u
touch foo_audio.mp3
touch foo_audio.ogg
touch foo_audio.pls
touch foo_audio.wav
touch foo_audio.wma
touch foo_config.cfg
touch foo_config.conf
touch foo_config.config
touch foo_config.ini
touch foo_crypto.kdb
touch foo_crypto.kdbx
touch foo_crypto.tc
touch foo_document.csv
touch foo_document.doc
touch foo_document.docx
touch foo_document.ods
touch foo_document.odt
touch foo_document.pdf
touch foo_document.rtf
touch foo_document.tsv
touch foo_document.xls
touch foo_document.xlsx
touch foo_exe.air
touch foo_exe.exe
touch foo_exe.jar
touch foo_exe.msi
touch foo_help.chm
touch foo_help.hlp
touch foo_image.bmp
touch foo_image.gif
touch foo_image.icl
touch foo_image.ico
touch foo_image.jpeg
touch foo_image.jpg
touch foo_image.pdn
touch foo_image.png
touch foo_image.tif
touch foo_plain.asc
touch foo_misc.bak
touch foo_misc.bar
touch foo_misc.bin
touch foo_misc.dat
touch foo_plain.diff
touch foo_misc.dll
touch foo_plain.eml
touch foo_misc.fon
touch foo_plain.log
touch foo_plain.markdown
touch foo_plain.md
touch foo_plain.nfo
touch foo_misc.org
touch foo_misc.reg
touch foo_misc.ttf
touch foo_plain.txt
touch foo_script.ahk
touch foo_script.bat
touch foo_script.ps1
touch foo_script.sh
touch foo_script.vbs
touch foo_source.c
touch foo_source.ino
touch foo_source.pde
touch foo_source.pl
touch foo_source.py
touch foo_source.xml
touch foo_video.3gp
touch foo_video.avi
touch foo_video.flv
touch foo_video.m4v
touch foo_video.mkv
touch foo_video.mov
touch foo_video.mp4
touch foo_video.mpeg
touch foo_video.mpg
touch foo_video.wmv
touch foo_web.cgi
touch foo_web.css
touch foo_web.htm
touch foo_web.html
touch foo_web.js
touch foo_web.json
touch foo_web.php
